### ISSUE TITLE
Conflict of interest form

### ISSUE THREAD

**Issue by gmyenni** [weecology/MATSS-startup#17]
http://research.ufl.edu/compliance/pdf/NSF1_DSR5_rev2.1.pdf

- [x] @skmorgane 

- [x] @ethanwhite 

- [x] @ha0ye

**Comment by ha0ye** [comment]
@gmyenni - can you add a link to the template for this that we need to sign.

**Comment by gmyenni** [comment]
https://drive.google.com/open?id=1d57R4nT4ZxkwLQ1cCaqcOoW-kOZzMVT1

**Comment by ethanwhite** [comment]
@gmyenni - is this something that you can compile from the COA documents or do we need to include other information?

**Comment by gmyenni** [comment]
Don't we send them to someone at UF who combines them, or are we doing that?
It is a separate template from the COA one. . .

**Comment by gmyenni** [comment]
And then there's this UF form: http://research.ufl.edu/compliance/pdf/NSF1_DSR5_rev2.1.pdf

**Comment by ethanwhite** [comment]
> Don't we send them to someone at UF who combines them, or are we doing that?

That was a special one time thing due to the size of the grant we were writing. We'll generally be on our own for all of this.

Also, I have a vague recollection that this was a special form for Macrosystems proposals. Probably worth checking the PAPPG to see if we need it for a normal solicitation:
https://www.nsf.gov/pubs/policydocs/pappg18_1/index.jsp

**Comment by gmyenni** [comment]
Okay, so then we just need the other form from each of you, that we send to Brandy? Conflict of interest form is on the list she sent us.

**Comment by ethanwhite** [comment]
Yes, I think that's right.
